# 开发环境配置
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/content_mind_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root

  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0

  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  # Elasticsearch配置
  elasticsearch:
    uris: http://localhost:9200
    username: 
    password: 

# 日志配置
logging:
  level:
    com.contentmind.platform: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 应用配置
app:
  upload:
    path: ./uploads/dev
  cache:
    default-ttl: 300 # 5分钟 (开发环境缓存时间短)